# Pandas Practice

## Goal
Learn Pandas step by step using datasets created with NumPy.

This notebook covers:
- Data inspection
- Missing value handling
- Filtering rows
- Sorting data
- Value counts
- Apply functions
- Grouping and aggregation
- Renaming and dropping columns

The datasets used in this notebook are artificially generated
using NumPy random functions for practice purposes.

# Common Setup

Import NumPy and Pandas libraries.

In [116]:
import numpy as np
import pandas as pd

# Dataset 1: Titanic-Like Passenger Dataset

## Purpose
Learn:
- data inspection
- filtering
- missing value handling
- grouping and aggregation

## Create Dataset

Generate a Titanic-like passenger dataset using Numpy

In [117]:
# Fix random values for reproducibility
np.random.seed(1)

#Create dataset with 200 rows
rows=200

In [118]:
#Create  DataFrame
df = pd.DataFrame({

 #Generate Sequential Passenger IDs
"Passenger Id": np.arange(1,rows+1),

 #Randomly select  passenger names
 "Name": np.random.choice(
     ["Mr. John", "Mrs. Anna", "Miss Emma", "Dr. Smith"],
     rows

     ),
 #Genearte Age Column with some missing values
 "Age": np.random.choice(

                        #Combine random ages with NaN values
                        np.append(

                                  #Generate 180 random ages between 1 and 79
                                  np.random.randint(1,80,180),

                                  #Add 20 missing values
                                   [np.nan]*20
                                 ),
                        #Select 200 rows randomly
                        rows
 ),


 #Randomly assign  gender values
 "Sex": np.random.choice(
     ["male","female"],
     rows
 ),


  #Randomly assign passenger classes
  "Pclass": np.random.choice(
      [1,2,3],
      rows
  ),


 #Generate random fare values between 10 and 500
 "Fare": np.round(

            #Generate random decimal values
            np.random.uniform(10,500,
                              rows),

            #Round values to 2 decimal places.
            2

 )

})

# View Data

In [119]:
#Display first 5 rows of the dataset
df.head()

   Passenger Id       Name   Age     Sex  Pclass    Fare
0             1  Mrs. Anna  40.0    male       2  461.14
1             2  Dr. Smith   NaN    male       1  333.43
2             3   Mr. John  75.0    male       1  348.14
3             4   Mr. John  63.0  female       2   92.36
4             5  Dr. Smith  39.0  female       1  346.02

In [120]:
#Display last 5 rows of the dataset
df.tail()

     Passenger Id       Name   Age     Sex  Pclass    Fare
195           196  Miss Emma  40.0    male       2  136.23
196           197  Dr. Smith  33.0  female       1  300.03
197           198  Mrs. Anna  75.0    male       3   53.22
198           199  Mrs. Anna   NaN    male       2  431.91
199           200  Miss Emma  33.0    male       3   45.51

In [121]:
#Display 3 random rows from dataset
df.sample(3)

     Passenger Id       Name   Age     Sex  Pclass    Fare
128           129   Mr. John  18.0    male       3  338.25
175           176   Mr. John  33.0  female       3  329.26
41             42  Mrs. Anna  36.0    male       1   47.32

# Inspect Structure

In [122]:
#Display number of rows and columns
df.shape

(200, 6)

In [123]:
# Display all Column names
df.columns

Index(['Passenger Id', 'Name', 'Age', 'Sex', 'Pclass', 'Fare'], dtype='object')

In [124]:
# Display dataset information and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Passenger Id  200 non-null    int64
 1   Name          200 non-null    object
 2   Age           182 non-null    float64
 3   Sex           200 non-null    object
 4   Pclass        200 non-null    int64
 5   Fare          200 non-null    float64
dtypes: float64(2), int64(2), object(2)
memory usage: 9.5+ KB

In [125]:
# Display statistical summary of numerical columns
df.describe()

       Passenger Id         Age      Pclass        Fare
count    200.000000  182.000000  200.000000  200.000000
mean     100.500000   43.318681    2.035000  251.249700
std       57.879185   22.078153    0.804369  146.847353
min        1.000000    1.000000    1.000000   11.250000
25%       50.750000   25.250000    1.000000  115.550000
50%      100.500000   41.000000    2.000000  265.430000
75%      150.250000   63.000000    3.000000  371.432500
max      200.000000   79.000000    3.000000  493.680000

# Handle Missing Data

In [126]:
#Count missing values in each column
df.isnull().sum()

Passenger Id     0
Name             0
Age             18
Sex              0
Pclass           0
Fare             0
dtype: int64

In [127]:
#Replace missing age values with average age
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [128]:
df["Age"].isnull().sum()

np.int64(0)

# Filtering Rows

In [129]:
# Display Passengers whose age is greater than 30
df[df["Age"]>30]

     Passenger Id       Name        Age     Sex  Pclass    Fare
0               1  Mrs. Anna  40.000000    male       2  461.14
1               2  Dr. Smith  43.318681    male       1  333.43
2               3   Mr. John  75.000000    male       1  348.14
3               4   Mr. John  63.000000  female       2   92.36
4               5  Dr. Smith  39.000000  female       1  346.02
..            ...        ...        ...     ...     ...     ...
195           196  Miss Emma  40.000000    male       2  136.23
196           197  Dr. Smith  33.000000  female       1  300.03
197           198  Mrs. Anna  75.000000    male       3   53.22
198           199  Mrs. Anna  43.318681    male       2  431.91
199           200  Miss Emma  33.000000    male       3   45.51

[140 rows x 6 columns]

In [130]:
# Display only female passengers
df[df["Sex"]=="female"]

     Passenger Id       Name        Age     Sex  Pclass    Fare
3               4   Mr. John  63.000000  female       2   92.36
4               5  Dr. Smith  39.000000  female       1  346.02
5               6  Mrs. Anna  26.000000  female       2  304.88
8               9  Dr. Smith  29.000000  female       3   44.05
10             11   Mr. John  77.000000  female       3  247.52
..            ...        ...        ...     ...     ...     ...
186           187   Mr. John  43.318681  female       1  148.20
190           191  Miss Emma  68.000000  female       1  367.68
191           192  Miss Emma  78.000000  female       3   12.94
193           194  Dr. Smith  43.318681  female       1   25.29
196           197  Dr. Smith  33.000000  female       1  300.03

[99 rows x 6 columns]

# Grouping & Aggregation

In [131]:
#Calculate average fare for each passenger class
df.groupby("Pclass")["Fare"].mean()

Pclass
1    237.222623
2    281.545775
3    232.200147
Name: Fare, dtype: float64

# Dataset 2: Student Performance Dataset

## Purpose
Learn:
- sorting
- value counts
- apply()
- conditional columns
- grouping

## Create Dataset

Generate a student performance dataset using NumPy.

In [132]:
np.random.seed(2)
rows = 150

In [133]:
df = pd.DataFrame({
    "StudentId": np.arange(1, rows + 1),
    "Age": np.random.randint(18, 30, rows),
    "Gender": np.random.choice(["male", "female"], rows),
    "Course": np.random.choice(["AI", "DS", "ML", "Python"], rows),
    "Marks": np.random.randint(35, 100, rows)
})

In [134]:
df.head()

   StudentId  Age  Gender Course  Marks
0          1   26    male     AI     65
1          2   26  female     DS     41
2          3   24    male     DS     56
3          4   29  female     ML     52
4          5   20  female     AI     72

# Sorting Data

In [135]:
# Sort students based marks in descending order
df.sort_values(by="Marks",ascending=False)

     StudentId  Age  Gender  Course  Marks
47          48   26  female      DS     99
30          31   26  female      ML     99
140        141   26  female      DS     99
145        146   25  female      ML     99
19          20   22  female  Python     98
..         ...  ...     ...     ...    ...
110        111   29  female      ML     38
40          41   28  female      ML     37
144        145   18  female  Python     37
14          15   22  female      ML     35
11          12   23  female      ML     35

[150 rows x 5 columns]

# Value Counts

In [136]:
#Count number of male and female students.
df["Gender"].value_counts()

Gender
female    84
male      66
Name: count, dtype: int64

# Apply Function

Create a Result column based on marks.
Students with marks greater than or equal to 50 are marked as Pass.

In [137]:
# Create Result column using apply and lambda
df["Result"]=df["Marks"].apply(lambda x:"Pass" if x>=50 else "Fail")

In [138]:
df["Result"].sample(10)

140    Pass
30     Pass
23     Pass
62     Pass
96     Pass
71     Pass
57     Pass
76     Pass
22     Pass
137    Pass
Name: Result, dtype: object

# Grouping

In [139]:
# Calculate average marks for each course
df.groupby("Course")["Marks"].mean()

Course
AI        68.185185
DS        64.611111
ML        62.125000
Python    68.282051
Name: Marks, dtype: float64

# Dataset 3: Employee Dataset

## Purpose
Learn:
- renaming columns
- dropping columns
- aggregation functions
- grouping operations

## Create Dataset

Generate an employee dataset using NumPy.

In [140]:
np.random.seed(3)
rows = 120

In [141]:
df = pd.DataFrame({
    "EmpId": np.arange(1, rows + 1),
    "Dept": np.random.choice(["HR", "IT", "Sales"], rows),
    "Salary": np.random.randint(30000, 150000, rows),
    "Gender": np.random.choice(["male", "female"], rows)
})

In [142]:
df.head()

   EmpId   Dept  Salary  Gender
0      1  Sales   36081  female
1      2     HR   56659    male
2      3     IT   53725    male
3      4     HR   54818    male
4      5     HR   58724  female

# Rename Columns

In [143]:
#Reanme Dept column to Department
df.rename(columns={"Dept":"Department"},inplace=True)

In [144]:
df.head()

   EmpId Department  Salary  Gender
0      1      Sales   36081  female
1      2         HR   56659    male
2      3         IT   53725    male
3      4         HR   54818    male
4      5         HR   58724  female

# Drop Columns

In [145]:
#Remove Gender column
df.drop("Gender",axis=1,inplace=True)

In [146]:
df.head()

   EmpId Department  Salary
0      1      Sales   36081
1      2         HR   56659
2      3         IT   53725
3      4         HR   54818
4      5         HR   58724

# Aggregation

In [147]:
df.groupby("Department")["Salary"].agg("mean","max")

Department
HR       85759.094340
IT       92223.166667
Sales    86745.483871
Name: Salary, dtype: float64